apiVersion: v2
dependencies:
- name: argo-cd
  repository: https://argoproj.github.io/argo-helm
  version: 7.3.11
description: |
  This chart installs and configures:

  * Argo CD official chart
  * A Grafana dashboard for Argo CD
  * An `OAuthClient` Kubernetes object if the OpenShift 4 option is enabled
name: ArgoCD
version: "0"
